#!/bin/bash -v
/usr/etc/venture/bin/dbmgr -optimize archivefile
/usr/etc/venture/bin/dbmgr -optimize archivemedia
/usr/etc/venture/bin/dbmgr -optimize archivepath
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_001
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_002
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_003
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_004
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_005
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_006
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_007
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_008
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_009
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_010
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_011
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_012
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_013
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_014
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_015
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_016
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_017
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_018
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_019
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_020
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_021
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_022
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_023
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_024
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_025
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_026
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_027
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_028
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_029
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_030
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_031
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_032
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_033
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_034
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_035
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_036
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_037
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_038
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_039
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_040
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_041
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_042
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_043
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_044
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_045
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_046
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_047
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_048
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_049
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_050
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_051
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_052
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_053
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_054
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_055
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_056
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_057
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_058
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_059
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_060
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_061
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_062
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_063
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_064
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_065
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_066
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_067
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_068
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_069
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_070
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_071
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_072
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_073
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_074
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_075
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_076
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_077
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_078
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_079
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_080
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_081
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_082
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_083
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_084
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_085
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_086
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_087
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_088
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_089
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_090
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_091
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_092
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_093
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_094
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_095
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_096
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_097
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_098
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_099
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_100
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_101
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_102
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_103
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_104
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_105
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_106
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_107
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_108
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_109
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_110
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_111
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_112
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_113
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_114
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_115
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_116
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_117
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_118
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_119
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_120
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_121
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_122
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_123
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_124
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_125
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_126
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_127
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_128
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_129
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_130
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_131
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_132
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_133
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_134
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_135
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_136
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_137
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_138
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_139
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_140
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_141
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_142
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_143
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_144
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_145
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_146
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_147
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_148
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_149
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_150
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_151
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_152
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_153
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_154
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_155
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_156
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_157
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_158
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_159
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_160
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_161
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_162
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_163
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_164
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_165
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_166
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_167
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_168
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_169
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_170
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_171
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_172
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_173
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_174
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_175
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_176
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_177
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_178
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_179
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_180
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_181
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_182
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_183
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_184
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_185
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_186
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_187
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_188
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_189
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_190
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_191
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_192
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_193
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_194
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_195
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_196
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_197
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_198
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_199
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_200
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_201
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_202
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_203
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_204
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_205
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_206
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_207
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_208
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_209
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_210
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_211
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_212
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_213
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_214
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_215
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_216
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_217
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_218
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_219
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_220
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_221
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_222
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_223
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_224
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_225
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_226
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_227
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_228
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_229
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_230
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_231
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_232
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_233
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_234
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_235
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_236
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_237
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_238
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_239
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_240
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_241
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_242
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_243
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_244
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_245
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_246
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_247
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_248
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_249
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_250
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_251
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_252
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_253
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_254
/usr/etc/venture/bin/dbmgr -optimize bigwebdata_255
/usr/etc/venture/bin/dbmgr -optimize event
/usr/etc/venture/bin/dbmgr -optimize file
/usr/etc/venture/bin/dbmgr -optimize keyword
/usr/etc/venture/bin/dbmgr -optimize keyword1
/usr/etc/venture/bin/dbmgr -optimize path
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_001
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_002
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_003
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_004
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_005
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_006
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_007
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_008
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_009
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_010
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_011
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_012
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_013
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_014
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_015
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_016
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_017
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_018
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_019
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_020
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_021
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_022
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_023
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_024
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_025
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_026
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_027
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_028
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_029
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_030
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_031
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_032
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_033
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_034
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_035
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_036
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_037
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_038
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_039
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_040
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_041
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_042
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_043
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_044
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_045
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_046
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_047
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_048
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_049
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_050
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_051
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_052
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_053
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_054
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_055
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_056
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_057
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_058
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_059
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_060
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_061
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_062
/usr/etc/venture/bin/dbmgr -optimize smallwebdata_063