
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid1/generalmills
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/anthem
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/centralgarden
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/conagra
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/dial
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/diamondfoods
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/dollargeneral
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/familydollar
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/faribaultfoods
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/ghb
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/henkel
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/hormel
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/mars
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/merck
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/nestle
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/otherclients
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/petsmart
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/pulmuone
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm /mn_raid2/safeway
