/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r1/generalmills
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/3m
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/anthem
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/centralgarden
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/conagra
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/dial
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/diamondfoods
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/dollargeneral
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/familydollar
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/faribaultfoods
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/ghb
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/henkel
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/hormel
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/mars
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/merck
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/nestle
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/otherclients
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/petsmart
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/pulmuone
/usr/etc/venture/bin/syncvoltodb -noarchpicts -delnorm  /r2/safeway

