#!/bin/csh -f
set d=/mn_raid2/input_output/Output\ Files/bsAcrobat\ PDF\ Schering\ Plough/bs_Real_Out
echo "$d/$2" >& /var/tmp/bsScheringPDFfile_name.out
/usr/etc/appletalk/ksmv "$1" "$d/$2"
chmod 666 "$d/$2"
/usr/etc/appletalk/kats -c -i "$d/$2"
