#!/bin/csh -f
set d=/mn_raid2/auto/Input\ Hot\ Folders/Cross\ Sells\ Nestle\ Staging
/usr/etc/appletalk/imagetox -xeps80 -r300 "$1" > "$d/$2:r".eps

chmod 777 "$d/$2:r".eps
chown root "$d/$2:r".eps
chgrp schawk_users "$d/$2:r".eps
